# Generated by Django 4.2.2 on 2023-07-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='proceso',
            name='juez_encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='participantes',
            field=models.ManyToManyField(related_name='procesos_participantes', to='radicados.participante'),
        ),
    ]
